name: Blacklist3 ☞ assets/Blacklist3

on:
  workflow_dispatch:

jobs:
  run_blacklist3:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # 获取完整历史

      # 新增：强制同步远程代码（应对仓库重建）
      - name: 强制同步远程代码
        run: git fetch --prune && git reset --hard origin/main

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # 直接运行脚本（无需安装额外Python包）
      - run: python assets/blacklist3/blacklist3.py

      - name: 强制推送结果文件
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          
          git add assets/blacklist3/result.txt
          
          if git diff --staged --quiet; then
            echo "无结果文件变更，跳过推送"
            exit 0
          fi
          
          git commit -m "Update Blacklist3 result: $(date +%Y%m%d)"
          
          # 优化冲突处理
          git pull origin main --rebase --autostash || {
            echo "变基冲突，自动用远程最新代码覆盖本地";
            git rebase --abort;
            git pull origin main --force;
          }
          git push origin main --force-with-lease || git push origin main -f
          echo "推送成功！"
